server:
  webhook:
    enabled: true
    secret_token: <strong_arbitrary_secret_token>

gitlab:
  url: https://gitlab.com
  token: <your_token>

projects:
  # Configure a project on which you are authorized to configure webhooks
  - name: <your_project_path_with_namespace>
